POLYGONS_3_20 = [
  {"name": "triangle", "num_sides": 3},
  {"name": "square", "num_sides": 4},
  {"name": "pentagon", "num_sides": 5},
  {"name": "hexagon", "num_sides": 6},
  {"name": "heptagon", "num_sides": 7},
  {"name": "octagon", "num_sides": 8},
  {"name": "nonagon", "num_sides": 9},
  {"name": "decagon", "num_sides": 10},
  {"name": "undecagon", "num_sides": 11},
  {"name": "dodecagon", "num_sides": 12},
  {"name": "tridecagon", "num_sides": 13},
  {"name": "tetradecagon", "num_sides": 14},
  {"name": "pentadecagon", "num_sides": 15},
  {"name": "hexadecagon", "num_sides": 16},
  {"name": "heptadecagon", "num_sides": 17},
  {"name": "octadecagon", "num_sides": 18},
  {"name": "enneadecagon", "num_sides": 19},
  {"name": "icosagon", "num_sides": 20},
]